### ISSUE TITLE
Clean numpy install needs libgfortran=3, defaults to 4 and breaks

### ISSUE THREAD

**Issue by poplarShift** [conda-forge/numpy-feedstock#127]
Works:
```
conda create -n numpy3 -c conda-forge numpy libgfortran=3
conda activate numpy3
python -c "import numpy"
```

Fails:
```
conda create -n numpy -c conda-forge numpy
conda activate numpy
python -c "import numpy"
```

With:
```
Traceback (most recent call last):
  File "/Users/doppler/anaconda3/envs/numpy/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "/Users/doppler/anaconda3/envs/numpy/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/Users/doppler/anaconda3/envs/numpy/lib/python3.7/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/doppler/anaconda3/envs/numpy/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /Users/doppler/anaconda3/envs/numpy/lib/libopenblas.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/doppler/anaconda3/envs/numpy/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/doppler/anaconda3/envs/numpy/lib/python3.7/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

[...]

Original error was: dlopen(/Users/doppler/anaconda3/envs/numpy/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libgfortran.3.dylib
  Referenced from: /Users/doppler/anaconda3/envs/numpy/lib/libopenblas.dylib
  Reason: image not found
```

Edit: 
The same as #126... didn't see that one in time due to its title. I'm on macos and
```
conda --version
conda 4.6.2
```

**Comment by horta** [comment]
Same here.

**Comment by beckermr** [comment]
This is fixed! We had a buggy patch on the repo data but it works now. The patches only get applied to newly created envs.
