### ISSUE TITLE
update to numpy-1.16.4 breaks numpy import "older version of numpy detected"

### ISSUE THREAD

**Issue by akrherz** [conda-forge/numpy-feedstock#159]
Issue:  A currently working numpy=1.16.3 install breaks after updating to numpy=1.16.4

```
import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/prod/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/opt/miniconda3/envs/prod/lib/python3.6/site-packages/numpy/core/__init__.py", line 91, in <module>
    raise ImportError(msg.format(path))
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/opt/miniconda3/envs/prod/lib/python3.6/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/miniconda3/envs/prod:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
alembic                   1.0.8                      py_0    conda-forge
apiclient                 1.0.3                    pypi_0    pypi
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astroid                   2.2.5                    py36_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atk                       2.25.90           hb9dd440_1002    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
automat                   0.7.0                    pypi_0    pypi
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcrypt                    3.1.4            py36h470a237_0    conda-forge
beautifulsoup4            4.7.1                 py36_1001    conda-forge
bitstring                 3.1.5                    pypi_0    pypi
black                     18.6b4                   pypi_0    pypi
blas                      2.10                   openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     1.1.0                    py36_0    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bottleneck                1.2.1           py36h3010b51_1001    conda-forge
boxsdk                    1.5.5                    pypi_0    pypi
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cachetools                2.1.0                    pypi_0    pypi
cairo                     1.16.0            ha4e643d_1000    conda-forge
cartopy                   0.17.0          py36h0aa2c8f_1004    conda-forge
cdo                       1.9.6             hd104f1c_1006    conda-forge
cdsapi                    0.1.3                    pypi_0    pypi
certifi                   2019.3.9                 py36_0    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cf_units                  2.0.1           py36h3010b51_1002    conda-forge
cffi                      1.12.3           py36h8022711_0    conda-forge
cfgrib                    0.9.6.2                    py_0    conda-forge
cftime                    1.0.3.4         py36h3010b51_1000    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.0.0                      py_0    conda-forge
cmarkgfm                  0.4.2            py36h14c3975_2    conda-forge
codecov                   2.0.15                   pypi_0    pypi
configurable-http-proxy   1.3.0                         0    conda-forge
consistent-hash-git       0.3                      pypi_0    pypi
constantly                15.1.0                     py_0    conda-forge
coverage                  4.5.3            py36h14c3975_0    conda-forge
coveralls                 1.5.1                      py_0    conda-forge
cryptography              2.6.1            py36h72c5cf5_0    conda-forge
cryptography-vectors      2.6.1                      py_0    conda-forge
curl                      7.64.1               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.7           py36he1b5a44_0    conda-forge
cytoolz                   0.9.0.1         py36h14c3975_1001    conda-forge
dask                      1.2.2                      py_0    conda-forge
dask-core                 1.2.2                      py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
descartes                 1.1.0                      py_3    conda-forge
distributed               1.28.0                   py36_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.14                  py36_1001    conda-forge
dropbox                   9.3.0                      py_0    conda-forge
eccodes                   2.12.3               h4fa793d_1    conda-forge
ecmwf_grib                1.14.7                        2    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
enum34                    1.1.6                    pypi_0    pypi
ephem                     3.7.6.0         py36h14c3975_1001    conda-forge
esmf                      7.1.0             hdfb41a0_1004    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
feedgen                   0.7.0                    pypi_0    pypi
fftw                      3.3.8           nompi_h7f3a6c3_1105    conda-forge
fiona                     1.8.6            py36hf242f0b_3    conda-forge
flake8                    3.7.7                    py36_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fribidi                   1.0.5             h14c3975_1000    conda-forge
future                    0.16.0                   pypi_0    pypi
g2clib                    1.6.0                hf3f1b0b_9    conda-forge
gdal                      2.4.1            py36hf242f0b_0    conda-forge
gdata                     3.0.0                    pypi_0    pypi
gdk-pixbuf                2.36.12           h49783d7_1002    conda-forge
geographiclib             1.49                       py_0    conda-forge
geojson                   2.4.1                      py_0    conda-forge
geopandas                 0.5.0                      py_2    conda-forge
geopy                     1.19.0                     py_0    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.4.3             h1105359_1000    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gobject-introspection     1.58.2          py36h2da5eee_1000    conda-forge
google-api-python-client  1.7.4                    pypi_0    pypi
google-auth               1.5.0                    pypi_0    pypi
google-auth-httplib2      0.0.3                    pypi_0    pypi
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gsl                       2.4               h294904e_1006    conda-forge
gst-plugins-base          1.14.4            hdf3bae2_1001    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
gtk2                      2.24.31           hb68c50a_1001    conda-forge
h5netcdf                  0.7.1                      py_0    conda-forge
h5py                      2.9.0           nompi_py36hf008753_1102    conda-forge
harfbuzz                  2.4.0                h37c48d4_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
hdfeos2                   2.20              h64bfcee_1000    conda-forge
hdfeos5                   5.1.16               hccfc538_4    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
httplib2                  0.11.3                   pypi_0    pypi
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
iembot                    0.1.0                    pypi_0    pypi
imagesize                 1.1.0                      py_0    conda-forge
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2019.3                      199  
ipykernel                 5.1.0           py36h24bf2e0_1002    conda-forge
ipython                   7.5.0            py36h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.20                   py36_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.13.3                   py36_0    conda-forge
jenks                     1.0                      pypi_0    pypi
jinja2                    2.10.1                     py_0    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.0.1                    py36_0    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterhub                1.0.0                    py36_0    conda-forge
jupyterlab                0.35.6                   py36_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
kealib                    1.4.10            h1978553_1003    conda-forge
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.7                    pypi_0    pypi
keras-preprocessing       1.0.9                    pypi_0    pypi
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
lazy-object-proxy         1.4.1            py36h516909a_0    conda-forge
libaec                    1.0.4                hf484d3e_0    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.64.1               hda55be3_0    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.4.1                hdb8f723_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
liblapacke                3.8.0               10_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.3                 h4e4e079_0    conda-forge
libprotobuf               3.7.1                h8b12597_0    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libspatialindex           1.9.0                he1b5a44_0    conda-forge
libspatialite             4.3.0a            hb5ec416_1026    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
libxslt                   1.1.32            h4785a14_1002    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.3.3            py36h7ec2d77_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
mako                      1.0.7                      py_1    conda-forge
mapclassify               2.0.1                      py_0    conda-forge
mapscript                 7.3.0                    pypi_0    pypi
markupsafe                1.1.1            py36h14c3975_0    conda-forge
matplotlib                3.1.0                    py36_1    conda-forge
matplotlib-base           3.1.0            py36hfd891ef_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
metar                     1.7.0                    pypi_0    pypi
metpy                     0.10.0                py36_1001    conda-forge
mistune                   0.8.4           py36h14c3975_1000    conda-forge
mkl                       2019.3                      199  
mkl_fft                   1.0.13           py36h516909a_1    conda-forge
mkl_random                1.0.4            py36hf2d7682_0    conda-forge
mock                      3.0.5                    py36_0    conda-forge
mod-wsgi                  4.6.4                    pypi_0    pypi
more-itertools            4.3.0                 py36_1000    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1             h1c2f66e_1008    conda-forge
msgpack-python            0.6.1            py36h6bb024c_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nco                       4.8.0                hfb3d286_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf-fortran            4.4.5             hea25ff8_1000    conda-forge
netcdf4                   1.5.1.2          py36had58050_0    conda-forge
nodejs                    11.14.0              he1b5a44_1    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.7.8                    py36_0    conda-forge
numexpr                   2.6.9           py36h637b7d7_1000    conda-forge
numpy                     1.16.4           py36h95a1406_0    conda-forge
numpy-base                1.14.3           py36h2b20989_0  
nwnserver                 0.2                      pypi_0    pypi
oauth                     1.0.1                    pypi_0    pypi
oauth2client              4.1.2                    pypi_0    pypi
oauthlib                  3.0.1                      py_0    conda-forge
odfpy                     1.3.6                    pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.6                h6e990d7_2    conda-forge
openjpeg                  2.3.1                h58a6597_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
ossuuid                   1.6.2             hf484d3e_1000    conda-forge
owslib                    0.17.1                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
palettable                3.1.1                      py_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pandas                    0.24.2           py36hf484d3e_0    conda-forge
pandoc                    2.7.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
parso                     0.4.0                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
paste                     3.0.8                    py36_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pbr                       5.1.3                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pika                      1.0.1                      py_0    conda-forge
pillow                    6.0.0            py36he7afcd5_0    conda-forge
pint                      0.8.1                      py_1    conda-forge
pip                       19.1                     py36_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.11.0                     py_0    conda-forge
pockets                   0.6.2                    pypi_0    pypi
pooch                     0.1a3                    pypi_0    pypi
poppler                   0.67.0               h2ad7f00_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 hbeee2d4_0    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.7.1            py36he1b5a44_0    conda-forge
psutil                    5.6.2            py36h516909a_0    conda-forge
psycopg2                  2.8.2            py36h72c5cf5_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyasn1                    0.4.4                      py_1    conda-forge
pyasn1-modules            0.2.4                      py_0    conda-forge
pybufrkit                 0.2.7                    pypi_0    pypi
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pycurl                    7.43.0.2         py36h16ce93b_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.0                      py_0    conda-forge
pygrib                    2.0.4            py36hf3f1b0b_0    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pyiem                     0.9.0                    pypi_0    pypi
pyjwt                     1.7.1                      py_0    conda-forge
pykdtree                  1.3.1           py36h3010b51_1002    conda-forge
pyldm                     0.1.0                    pypi_0    pypi
pylint                    2.3.1                    py36_0    conda-forge
pynio                     1.5.5            py36h8b983ae_0    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pypandoc                  1.4                      pypi_0    pypi
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.6           py36hc0953d3_1000    conda-forge
pyqt                      5.9.2            py36hcca6a23_0    conda-forge
pyrsistent                0.15.2           py36h516909a_0    conda-forge
pyrss2gen                 1.1                      pypi_0    pypi
pysal                     2.0.0                      py_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
pytest                    4.5.0                    py36_0    conda-forge
pytest-cov                2.7.1                      py_0    conda-forge
pytest-mpl                0.10                       py_0    conda-forge
pytest-runner             4.4                        py_0    conda-forge
python                    3.6.7             h381d211_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python-memcached          1.59                       py_0    conda-forge
python-oauth2             1.1.0                      py_2    conda-forge
python-twitter            3.4.2                    pypi_0    pypi
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1              py36h14c3975_0    conda-forge
pyzmq                     18.0.1           py36hc4ba49a_1    conda-forge
qt                        5.9.7                h52cfd70_1    conda-forge
rasterio                  1.0.23           py36h5b3f9e8_0    conda-forge
rasterstats               0.13.1                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
readme_renderer           24.0                       py_0    conda-forge
reportlab                 3.5.21           py36h7d98c4e_0    conda-forge
requests                  2.21.0                py36_1000    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
rrdtool                   0.1.14                   pypi_0    pypi
rsa                       3.4.2                    pypi_0    pypi
rtree                     0.8.3           py36h666c49c_1002    conda-forge
scikit-learn              0.19.2                   pypi_0    pypi
scipy                     1.2.1            py36h09a28d5_1    conda-forge
seaborn                   0.9.0                      py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
service_identity          18.1.0                     py_0    conda-forge
setuptools                41.0.1                   py36_0    conda-forge
setuptools-markdown       0.2                      pypi_0    pypi
shapely                   1.6.4           py36h2afed24_1004    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
simplejson                3.16.1           py36h470a237_0    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
siphon                    0.8.0                 py36_1001    conda-forge
six                       1.12.0                py36_1000    conda-forge
smartsheet-python-sdk     1.3.4.dev3+ga1559f8          pypi_0    pypi
snowballstemmer           1.2.1                      py_1    conda-forge
snuggs                    1.4.3                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.1                    py36_0    conda-forge
sphinx                    2.0.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-napoleon    0.6.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
sqlalchemy                1.3.3            py36h516909a_0    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
statsmodels               0.9.0           py36h3010b51_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tempest-remap             2.0.3                h5f743cb_0    conda-forge
terminado                 0.8.2                    py36_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
textgenrnn                1.5.0                    pypi_0    pypi
tk                        8.6.9             h84994c4_1001    conda-forge
tlslite                   0.4.9                    pypi_0    pypi
toml                      0.9.4                    pypi_0    pypi
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py36h516909a_0    conda-forge
tox                       3.4.0                    pypi_0    pypi
tqdm                      4.32.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
twine                     1.13.0                     py_1    conda-forge
twisted                   19.2.0           py36h516909a_1    conda-forge
twittytwister             0.1.3                    pypi_0    pypi
twython                   3.7.0                      py_0    conda-forge
txyam2                    0.5.1+weasyl.2           pypi_0    pypi
typed-ast                 1.3.5            py36h516909a_0    conda-forge
typing                    3.6.4                    py36_0    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
unidecode                 1.0.22                   pypi_0    pypi
unixodbc                  2.3.7             h227dcee_1000    conda-forge
uritemplate               3.0.0                      py_1    conda-forge
urllib3                   1.24.2                   py36_0    conda-forge
util-linux                2.21                          0  
verde                     0.0.1a0+72.g9ae9091          pypi_0    pypi
virtualenv                16.0.0                   pypi_0    pypi
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.4                   py36_0    conda-forge
windrose                  1.6                      pypi_0    pypi
wordcloud                 1.5.0           py36h14c3975_1000    conda-forge
wrapt                     1.11.1           py36h14c3975_0    conda-forge
wrf-python                1.3.2            py36h6091dcd_0    conda-forge
xarray                    0.12.1                     py_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.1.8                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h516909a_1004    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.3.1             hf484d3e_1000    conda-forge
zict                      0.1.4                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
zope.interface            4.6.0           py36h14c3975_1000    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : prod
    active env location : /opt/miniconda3/envs/prod
            shell level : 1
       user config file : /home/akrherz/.condarc
 populated config files : /home/akrherz/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.6.7.final.0
       base environment : /opt/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/akrherz/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/akrherz/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.22.0 CPython/3.6.7 Linux/3.10.0-957.12.2.el7.x86_64 rhel/7.6 glibc/2.17
                UID:GID : 1000:1000
             netrc file : /home/akrherz/.netrc
           offline mode : False
```
</details>

```
$ cat ~/.condarc 
channel_priority: strict
channels:
  - conda-forge
  - defaults
```

**Comment by ocefpaf** [comment]
I'm on Linux and I just did:

```
conda create --name TEST python=3.7 numpy=1.16.3 --yes
conda activate TEST
python -c "import numpy as np; print(np.__version__)"
1.16.3

conda install numpy=1.16.4 --yes --quiet
python -c "import numpy as np; print(np.__version__)"
1.16.4
```

Same conda version and `.condarc` as you :-/

**Comment by isuruf** [comment]
Mixing defaults and conda-forge is not supported. (numpy from conda-forge and numpy-base from defaults)

**Comment by ocefpaf** [comment]
The odd thing is how 

```
numpy                     1.16.4           py36h95a1406_0    conda-forge
numpy-base                1.14.3           py36h2b20989_0  
```

happened with `strict` enabled! That is a quite complex env with many PyPI packages. I wonder if conda has enough metadata there to do a proper upgrade.

**Comment by akrherz** [comment]
Interesting, I able to remove `numpy-base`  and it did not seem to take the entire env with it :/
```
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /opt/miniconda3/envs/prod

  removed specs:
    - numpy-base


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libopenblas-0.3.6          |       h6e990d7_2         7.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         7.6 MB

The following packages will be REMOVED:

  numpy-base-1.14.3-py36h2b20989_0

The following packages will be UPDATED:

  libopenblas        pkgs/main::libopenblas-0.2.20-h9ac955~ --> conda-forge::libopenblas-0.3.6-h6e990d7_2


Proceed ([y]/n)? y


Downloading and Extracting Packages
libopenblas-0.3.6    | 7.6 MB    | ########################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
now `numpy=1.16.4` is OK.  I recall attempting to remove `numpy-base` many moons ago and it was not pleasant.  Will see how long it can be kept away now.  thanks for the help here!

**Comment by ocefpaf** [comment]
> Will see how long it can be kept away now. thanks for the help here!

As long as you start the env with `strict` `numpy-base` should never be installed unless explicitly requested. (But it will be incompatible with `conda-forge`'s `numpy`.)
