### ISSUE TITLE
whats the correct pinning for pypy

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/numpy-feedstock#192]
Issue:
I'm trying to build imagecodecs but I seem to be having trouble pinning numpy correctly for pypy.
```
(base) ✔ ~ 
12:54 $ conda create --name pypy_numpy pypy numpy=1.14
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/mark/miniconda3/envs/pypy_numpy

  added / updated specs:
    - numpy=1.14
    - pypy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-2.16                  |         openblas          10 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          10 KB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_llvm
  blas               conda-forge/linux-64::blas-2.16-openblas
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_2
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.4.5.1-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2020.4.5.1-py36hc560c46_0
  expat              conda-forge/linux-64::expat-2.2.9-he1b5a44_2
  gdbm               conda-forge/linux-64::gdbm-1.18-h0a1914f_1
  libblas            conda-forge/linux-64::libblas-3.8.0-16_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-16_openblas
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-7.5.0-hdf63c60_6
  liblapack          conda-forge/linux-64::liblapack-3.8.0-16_openblas
  liblapacke         conda-forge/linux-64::liblapacke-3.8.0-16_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.9-h5ec1e0e_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  llvm-openmp        conda-forge/linux-64::llvm-openmp-10.0.0-hc9558a2_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpy              pkgs/main/linux-64::numpy-1.14.6-py36hec00662_5
  numpy-base         pkgs/main/linux-64::numpy-base-1.14.6-py36h2f8d375_5
  openssl            conda-forge/linux-64::openssl-1.1.1g-h516909a_0
  pip                conda-forge/noarch::pip-20.1.1-py_1
  pypy               conda-forge/noarch::pypy-7.3.1-hc8dfbb8_2
  pypy3.6            conda-forge/linux-64::pypy3.6-7.3.1-h3e02ecb_1
  python             conda-forge/linux-64::python-3.6.9-2_73_pypy
  python_abi         conda-forge/linux-64::python_abi-3.6-1_pypy36_pp73
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-47.1.1-py36hc560c46_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006



Downloading and Extracting Packages
blas-2.16            | 10 KB     | ################################################################################################################ | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pypy_numpy
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) ✔ ~ 
12:55 $ conda activate pypy_numpy
(pypy_numpy) ✔ ~ 
12:55 $ python -c "import numpy"
Traceback (most recent call last):
  File "/home/mark/miniconda3/envs/pypy_numpy/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mark/miniconda3/envs/pypy_numpy/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/mark/miniconda3/envs/pypy_numpy/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/mark/miniconda3/envs/pypy_numpy/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/mark/miniconda3/envs/pypy_numpy/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/mark/miniconda3/envs/pypy_numpy/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray'

```

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/d46af2b1ae50566f07e08e6d4ad72f1c33785a4c/recipe/migrations/pypy.yaml#L30

**Comment by hmaarrfk** [comment]
got it.
