### ISSUE TITLE
numpy 1.11 results in image not found for openblas on OSX Sierra 10.12.6

### ISSUE THREAD

**Issue by jtratner** [conda-forge/numpy-feedstock#61]
Clean install of environment of numpy 1.11 with conda-forge channel results in broken build on OSX:

Error:
```
›› which python                                                                                                         10:22 Sep 7
/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/bin/python
(test-numpy11) jtratner on C11552 in test-numpy11/on use-conda
››                                                                                                                      10:22 Sep 7
(test-numpy11) jtratner on C11552 in test-numpy11/on use-conda
›› python -c 'import numpy'                                                                                             10:22 Sep 7
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: dlopen(/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/python2.7/site-packages/numpy/core/multiarray.so, 2): Library not loaded: @rpath/libopenblas-r0.2.18.dylib
  Referenced from: /Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/python2.7/site-packages/numpy/core/multiarray.so
  Reason: image not found
(test-numpy11) jtratner on C11552 in test-numpy11/on use-conda
›› ls /Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/openblas*                                               10:22 Sep 7
zsh: no matches found: /Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/openblas*
(test-numpy11) jtratner on C11552 in test-numpy11/on use-conda
›› ls /Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/libopen*                                                10:22 Sep 7
/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/libopenblas.a
/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/libopenblas.dylib
/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/libopenblasp-r0.2.18.a
/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/lib/libopenblasp-r0.2.18.dylib
```

openblas 0.2.18 is listed as installed, but for some reason doesn't add in the correct dylib

I reproduced this from installing a completely clean miniconda and then running the following
```
jnstalling miniconda locally to .conda...
--2017-09-07 22:20:38--  https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh
Resolving repo.continuum.io... 104.16.18.10, 104.16.19.10, 2400:cb00:2048:1::6810:130a, ...
Connecting to repo.continuum.io|104.16.18.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 22438628 (21M) [application/x-sh]
Saving to: ‘miniconda.sh’

miniconda.sh        100%[===================>]  21.40M  18.1MB/s    in 1.2s

2017-09-07 22:20:39 (18.1 MB/s) - ‘miniconda.sh’ saved [22438628/22438628]

PREFIX=/Users/jtratner/test-numpy11/.conda
installing: python-2.7.13-0 ...
installing: asn1crypto-0.22.0-py27_0 ...
installing: cffi-1.10.0-py27_0 ...
installing: conda-env-2.6.0-0 ...
installing: cryptography-1.8.1-py27_0 ...
installing: enum34-1.1.6-py27_0 ...
installing: idna-2.5-py27_0 ...
installing: ipaddress-1.0.18-py27_0 ...
installing: openssl-1.0.2l-0 ...
installing: packaging-16.8-py27_0 ...
installing: pycosat-0.6.2-py27_0 ...
installing: pycparser-2.17-py27_0 ...
installing: pyopenssl-17.0.0-py27_0 ...
installing: pyparsing-2.1.4-py27_0 ...
installing: readline-6.2-2 ...
installing: requests-2.14.2-py27_0 ...
installing: ruamel_yaml-0.11.14-py27_1 ...
installing: setuptools-27.2.0-py27_0 ...
installing: six-1.10.0-py27_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.3.21-py27_0 ...
installing: pip-9.0.1-py27_1 ...
installing: wheel-0.29.0-py27_0 ...
Python 2.7.13 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
jtratner on C11552 in test-numpy11/on use-conda
›› .conda/bin/conda create -n test-numpy11                                                                              10:20 Sep 7
Fetching package metadata .........
Solving package specifications:
Package plan for installation in environment /Users/jtratner/test-numpy11/.conda/envs/test-numpy11:

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate test-numpy11
#
# To deactivate this environment, use:
# > source deactivate test-numpy11
#
jtratner on C11552 in test-numpy11/on use-conda
›› source .conda/bin/activate test-numpy11 && .conda/bin/conda install -c conda-forge numpy==1.11                       10:21 Sep 7
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/jtratner/test-numpy11/.conda/envs/test-numpy11:

The following NEW packages will be INSTALLED:

    blas:            1.1-openblas                  conda-forge
    ca-certificates: 2017.7.27.1-0                 conda-forge
    certifi:         2017.7.27.1-py27_0            conda-forge
    libgfortran:     3.0.0-0                       conda-forge
    ncurses:         5.9-10                        conda-forge
    numpy:           1.11.0-py27_blas_openblas_201 conda-forge [blas_openblas]
    openblas:        0.2.18-6                      conda-forge
    openssl:         1.0.2l-0                      conda-forge
    pip:             9.0.1-py27_0                  conda-forge
    python:          2.7.13-1                      conda-forge
    readline:        6.2-0                         conda-forge
    setuptools:      36.3.0-py27_0                 conda-forge
    sqlite:          3.13.0-1                      conda-forge
    tk:              8.5.19-2                      conda-forge
    wheel:           0.29.0-py27_0                 conda-forge
    zlib:            1.2.11-0                      conda-forge

Proceed ([y]/n)? y

ca-certificate 100% |####################################################################################| Time: 0:00:00 514.32 kB/s
libgfortran-3. 100% |####################################################################################| Time: 0:00:00   1.56 MB/s
ncurses-5.9-10 100% |####################################################################################| Time: 0:00:00   1.72 MB/s
sqlite-3.13.0- 100% |####################################################################################| Time: 0:00:00   4.36 MB/s
tk-8.5.19-2.ta 100% |####################################################################################| Time: 0:00:00   6.63 MB/s
zlib-1.2.11-0. 100% |####################################################################################| Time: 0:00:00  23.15 MB/s
openblas-0.2.1 100% |####################################################################################| Time: 0:00:01   8.93 MB/s
openssl-1.0.2l 100% |####################################################################################| Time: 0:00:00   7.96 MB/s
readline-6.2-0 100% |####################################################################################| Time: 0:00:00   3.93 MB/s
blas-1.1-openb 100% |####################################################################################| Time: 0:00:00   1.30 MB/s
python-2.7.13- 100% |####################################################################################| Time: 0:00:01   7.67 MB/s
certifi-2017.7 100% |####################################################################################| Time: 0:00:00   2.61 MB/s
numpy-1.11.0-p 100% |####################################################################################| Time: 0:00:00   4.74 MB/s
setuptools-36. 100% |####################################################################################| Time: 0:00:00   2.93 MB/s
wheel-0.29.0-p 100% |####################################################################################| Time: 0:00:00 221.57 kB/s
pip-9.0.1-py27 100% |####################################################################################| Time: 0:00:00   2.82 MB/s
which python
(test-numpy11) jtratner on C11552 in test-numpy11/on use-conda
›› which python                                                                                                         10:22 Sep 7
/Users/jtratner/test-numpy11/.conda/envs/test-numpy11/bin/python
```

**Comment by jakirkham** [comment]
Any reason not to use `numpy` 1.11.3?

**Comment by jtratner** [comment]
I'm trying to get pymc 2.3.6 installed with numpy and pandas :( . I think only numpy 1.11 will work with pymc 2.3.6

**Comment by jakirkham** [comment]
Right. Though it is atypical for a package to pin down to the patch release. With NumPy, we definitely avoid pinning to the patch release (only pin to major minor) in conda-forge. So would upgrading `numpy` 1.11.0 to `numpy` 1.11.3 cause other issues?

**Comment by jtratner** [comment]
@jakirkham - yep - numpy 1.11.3 works! Not sure how I ended up in a state where I was pinning to 1.11 - thanks for the help! (been futzing around with this for a while :P)

**Comment by jtratner** [comment]
ah man thank you SO much @jakirkham!! I think my problem is resolved - I'd just wrongly pinned to numpy 1.11.0

**Comment by jakirkham** [comment]
No worries. Glad to help. 😄

**Comment by jakirkham** [comment]
As a note, was able to reproduce this issue with the `numpy` 1.11.0 package. So that package is definitely broken somehow. Not sure if it merits further investigation if `numpy` 1.11.3 works just as well. However if there are other reasons to prefer `numpy` 1.11.0, happy to discuss further.

**Comment by jtratner** [comment]
Nope - I'm all good - it's just painful to use that old version of pymc
