### ISSUE TITLE
Windows 64 numpy 1.14 with openblas broken

### ISSUE THREAD

**Issue by j08lue** [conda-forge/numpy-feedstock#78]
I am unable to find existing issues covering this: When I on Windows 64 install `numpy` from `conda-forge`, I get a broken installation. I assume it is related to `openblas`.

### `conda list` 

```
#
blas                      1.1                    openblas    conda-forge
certifi                   2017.11.5                py36_0    conda-forge
libflang                  5.0.0             vc14_20180207  [vc14]  conda-forge
numpy                     1.14.0          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.20                   vc14_7  [vc14]  conda-forge
pip                       9.0.1                    py36_1    conda-forge
python                    3.6.4                         0    conda-forge
setuptools                38.4.0                   py36_0    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.30.0                   py36_2    conda-forge
wincertstore              0.2                      py36_0    conda-forge
```

### `conda info`

```
Current conda install:

               platform : win-64
          conda version : 4.3.32
       conda is private : False
      conda-env version : 4.3.32
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.18.4
       root environment : C:\Users\josl\AppData\Local\Continuum\Miniconda3  (writable)
    default environment : C:\Users\josl\AppData\Local\Continuum\Miniconda3\envs\numpy-openblas
       envs directories : C:\Users\josl\AppData\Local\Continuum\Miniconda3\envs
                          C:\Users\josl\AppData\Local\conda\conda\envs
                          C:\Users\josl\.conda\envs
          package cache : C:\Users\josl\AppData\Local\Continuum\Miniconda3\pkgs
                          C:\Users\josl\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\josl\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.32 requests/2.18.4 CPython/3.6.1 Windows/10 Windows/10.0.16299
          administrator : False
```

### `python -c "import numpy"`
```
Traceback (most recent call last):
  File "C:\Users\josl\AppData\Local\Continuum\Miniconda3\envs\numpy-openblas\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\josl\AppData\Local\Continuum\Miniconda3\envs\numpy-openblas\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\josl\AppData\Local\Continuum\Miniconda3\envs\numpy-openblas\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\josl\AppData\Local\Continuum\Miniconda3\envs\numpy-openblas\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\josl\AppData\Local\Continuum\Miniconda3\envs\numpy-openblas\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\josl\AppData\Local\Continuum\Miniconda3\envs\numpy-openblas\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.
```

For what it is worth, `numpy` version `1.13` works.

**Comment by ocefpaf** [comment]
Thanks for the report. I'll put them in a "broken" label so we can take a better look at the issue later.

@isuruf do you think it is an easy fix?

**Comment by isuruf** [comment]
cc @xoviat

**Comment by xoviat** [comment]
I can't reproduce this issue. I suspect the user has VS2015 Update 2 installed (or older). I need a procmon logfile in order to understand what's happening.

**Comment by xoviat** [comment]
Fixed in conda-forge/flang-feedstock@c5c37443da987884280bfbe0a54fca4e99d4198c

**Comment by xoviat** [comment]
cc @ocefpaf. Would you mind unlabeling the packages since the issue has been resolved?

**Comment by ocefpaf** [comment]
Done!

**Comment by j08lue** [comment]
Thanks for the quick action, guys. When I now install `numpy`, I get this configuration that works fine:
```
(...\Miniconda3) C:\Users\josl>conda create -n nptest python=3 numpy
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment ...\Miniconda3\envs\nptest:

The following NEW packages will be INSTALLED:

    certifi:        2018.1.18-py36_0      conda-forge
    icc_rt:         2017.0.4-h97af966_0
    intel-openmp:   2018.0.0-hd92c6cd_8
    mkl:            2018.0.1-h2108138_4
    numpy:          1.14.0-py36h4a99626_1
    pip:            9.0.1-py36_1          conda-forge
    python:         3.6.4-0               conda-forge
    setuptools:     38.5.1-py36_0         conda-forge
    vc:             14-0                  conda-forge
    vs2015_runtime: 14.0.25420-0          conda-forge
    wheel:          0.30.0-py36_2         conda-forge
    wincertstore:   0.2-py36_0            conda-forge
```

So no `openblas` at all. Why not, I wonder?

(I'll close this, as the issue is resolved.)

**Comment by ocefpaf** [comment]
@j08lue we remove the packages for now. We are testing it further and hopefully they will be back up soon.
